name: genialdesk-server

services:
  hbbs:
    container_name: genialdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r hjb0aa97v4s.sn.mynetname.net:21117
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped

  hbbr:
    container_name: genialdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
